# Generated by Django 3.1.4 on 2021-01-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmovies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcoming',
            name='picture',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
